export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";
export const UPDATE_LOADING_STATUS = "UPDATE_LOADING_STATUS";

export const FETCH_COLLECTION_START = "FETCH_COLLECTION_START";
export const FETCH_COLLECTION_SUCCSES = "FETCH_COLLECTION_SUCCSES";
export const FETCH_COLLECTION_FAILURE = "FETCH_COLLECTION_FAILURE";
